import React from 'react';
import { ResourceLayout } from '../../components/layout/ResourceLayout';

const pageData = [
  [
    "1",
    "I",
    "0202, 0203,\n0204, 0205,\n0206, 0207,\n0208, 0209,\n0210",
    "All goods [other than fresh or chilled] pre-packaged and labelled.",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "2",
    "I",
    "0303, 0304,0305, 0306,\n0307, 0308,\n0309",
    "All goods [other than fresh or chilled] pre-packaged and labelled.",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "3",
    "I",
    "",
    "[Omitted]",
    "",
    " ",
    "",
    " ",
    "",
    ""
  ],
  [
    "4",
    "I",
    "",
    "[Omitted]",
    "",
    " ",
    "",
    " ",
    "",
    ""
  ],
  [
    "5",
    "I",
    "",
    "[Omitted",
    "",
    " ",
    "",
    " ",
    "",
    ""
  ],
  [
    "6",
    "I",
    "",
    "[Omitted]",
    "",
    " ",
    "",
    " ",
    "",
    ""
  ],
  [
    "7",
    "I",
    "401",
    "Ultra High Temperature (UHT) milk",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "8",
    "I",
    "402",
    "Milk  and  cream,  concentrated  or  containing  added  sugar or   other   sweetening   matter,   including   skimmed   milk\npowder, milk food for babies [other than condensed milk]",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "9",
    "I",
    "403",
    "Yoghurt; Cream, kephir and other fermented or acidified milk and  cream,  whether  or  not  concentrated  or  containing  added sugar  or  other  sweetening  matter  or  flavored  or  containing\nadded fruit, nuts or cocoa",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "9A",
    "I",
    "403",
    "Curd, Lassi, Butter milk, pre-packaged and labelled",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "10",
    "I",
    "404",
    "Whey,  whether  or  not  concentrated  or  containing  added sugar  or  other  sweetening  matter;  products  consisting  of natural milk constituents, whether or not containing added sugar or other sweetening matter, not elsewhere specified or included",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "11",
    "I",
    "406",
    "Chena  or  paneer pre-packaged and labelled",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "12",
    "I",
    "408",
    "Birds'  eggs,  not  in  shell,  and  egg  yolks,  fresh,  dried, cooked  by  steaming  or  by  boiling  in  water,  moulded, frozen or otherwise  preserved,  whether  or  not  containing\nadded sugar or other sweetening matter.",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "13",
    "I",
    "409",
    "Natural honey pre-packaged and labelled",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "14",
    "I",
    "410",
    "Insects  and  other  edible  products  of  animal  origin,  not\nelsewhere specified or included",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "15",
    "I",
    "502",
    "Pigs',  hogs'  or  boars'  bristles  and  hair;  badger  hair  and\nother brush making hair; waste of such bristles or hair.",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "16",
    "I",
    "504",
    "All goods [other than fresh or chilled] pre-packaged and labelled.",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "17",
    "I",
    "505",
    "Skins and other parts of birds, with their feathers or down, feathers   and   parts   of   feathers   (whether   or   not   with trimmed   edges)   and   down,   not   further   worked   than cleaned,  disinfected  or  treated  for  preservation;  powder",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "18",
    "I",
    "0507\n[Except 050790]",
    "Ivory,   tortoise-shell,   whalebone   and   whalebone   hair,\nhorns, unworked or simply prepared but not cut to shape; powder and waste of these products.",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "19",
    "I",
    "508",
    "Coral and similar materials, unworked or simply prepared but not otherwise worked; shells of molluscs, crustaceans or   echinoderms   and   cuttle-bone,   unworked  or   simply\nprepared but not cut to shape, powder and waste thereof.",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "20",
    "I",
    "510",
    "Ambergris,  castoreum,  civet  and  musk; cantharides; bile, whether  or  not  dried;  glands  and  other  animal  products used in the preparation of pharmaceutical products, fresh,\nchilled, frozen or otherwise provisionally preserved.",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "21",
    "I",
    "511",
    "Animal products not elsewhere specified or included; dead\nanimals of Chapter 1 or 3, unfit  for human consumption, other than semen including frozen semen.",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "22",
    "I",
    "7",
    "Herb,  bark,  dry  plant,  dry  root,  commonly  known  as\njaribooti and dry flower",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "23",
    "I",
    "",
    "[Omitted]",
    "",
    " ",
    "",
    " ",
    "",
    ""
  ],
  [
    "24",
    "I",
    "",
    "[Omitted]",
    "",
    " ",
    "",
    " ",
    "",
    ""
  ],
  [
    "25",
    "I",
    "713",
    "Dried   leguminous   vegetables,   shelled,   whether   or   not skinned or split   pre-packaged and labelled.",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "26",
    "I",
    "714",
    "Manioc,  arrowroot,  salep,  Jerusalem  artichokes,  sweet potatoes and  similar  roots and tubers with high starch or inulin content, frozen, whether or not sliced or in the form of pellets pre-packaged and labelled.",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "27",
    "I",
    "801",
    "Cashew    nuts,    whether   or   not    shelled    or   peeled,\ndesiccated coconuts",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "28",
    "I",
    "802",
    "Dried areca nuts, whether or not shelled or peeled",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "29",
    "I",
    "0802,\n0813",
    "Dried  chestnuts  (singhada),  whether  or  not  shelled  or peeled",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "29A",
    "I",
    "802",
    "Walnuts, whether or not shelled",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "30",
    "I",
    "8",
    "Dried makhana, whether or not shelled or peeled pre-packaged and labelled.",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "30A",
    "I",
    "804",
    "Mangoes sliced, dried",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "31",
    "I",
    "806",
    "Grapes, dried, and raisins",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "32",
    "I",
    "811",
    "Fruit and nuts, uncooked or cooked by steaming or boiling\nin water, frozen, whether or not containing added sugar or other sweetening matter",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "33",
    "I",
    "812",
    "Fruit  and  nuts,  provisionally  preserved  (for  example,  by sulphur dioxide gas, in brine,  in sulphur water or in other preservative  solutions),  but  unsuitable  in  that  state  for\nimmediate consumption",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "33A",
    "I",
    "",
    "[Omitted]",
    "",
    " ",
    "",
    " ",
    "",
    ""
  ],
  [
    "34",
    "I",
    "814",
    "Peel  of  citrus  fruit  or  melons  (including  watermelons), frozen,   dried   or   provisionally   preserved   in   brine,   in\nsulphur water or in other preservative solutions",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "35",
    "I",
    "901",
    "Coffee  roasted,  whether  or  not  decaffeinated coffee\nhusks  and  skins;  coffee  substitutes  containing  coffee  in any proportion [other than coffee beans not roasted]",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "36",
    "I",
    "902",
    "Tea,  whether  or  not  flavoured  [other  than  unprocessed\ngreen leaves of tea",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "37",
    "I",
    "903",
    "Maté",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "38",
    "I",
    "904",
    "Pepper  of  the  genus  Piper;  dried  or  crushed  or  ground\nfruits of the genus Capsicum or of the genus Pimenta",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "39",
    "I",
    "905",
    "Vanilla",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "40",
    "I",
    "906",
    "Cinnamon and cinnamon-tree flowers",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "41",
    "I",
    "907",
    "Cloves (whole fruit, cloves and stems)",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "42",
    "I",
    "908",
    "Nutmeg, mace and cardamoms",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "43",
    "I",
    "909",
    "Seeds   of   anise,   badian,   fennel,   coriander,   cumin   or\ncaraway; juniper berries [other than of seed quality]",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "44",
    "I",
    "0910 [other\nthan 0910 11\n10, 0910 30\n10]",
    "Ginger    other    than    fresh    ginger,    saffron,    turmeric (curcuma)  other  than  fresh  turmeric,  thyme,  bay  leaves, curry and other spices",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "45",
    "I",
    "10",
    "All goods i.e. cereals pre-packaged and labelled.",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ],
  [
    "46",
    "I",
    "1001",
    "Wheat  and  meslin pre-packaged and labelled.",
    "0.025",
    " ",
    "0.025",
    " ",
    "0.05",
    ""
  ]
];

export const GstHsnCodes: React.FC = () => {
  return (
    <ResourceLayout 
      title="Gst Hsn Codes"
      description="View and search through Gst Hsn Codes documents."
      data={pageData}
      type="table"
    />
  );
};
