import React from 'react';
import { ResourceLayout } from '../../components/layout/ResourceLayout';

const LinkNode = <a href="https://www.incometaxindia.gov.in/income-tax-act" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--primary-light)', textDecoration: 'underline' }}>Link</a>;

const pageData: React.ReactNode[][] = [
  ["1", "Short Title & Extent", "Defines the name of the Act and its territorial applicability across India.", LinkNode],
  ["2", "Statutory Definitions", "Comprehensive legal interpretations of core terms used throughout the Act.", LinkNode],
  ["3", "Previous Year", "Defines the uniform financial year during which income is earned.", LinkNode],
  ["4", "Basis of Charge", "The core charging section that empowers the levy of income tax on total income.", LinkNode],
  ["5", "Scope of Total Income", "Dictates tax liability boundaries based on whether income is received, accrued, or deemed so.", LinkNode],
  ["6", "Residential Status", "Outlines physical stay criteria to classify taxpayers as Resident, ROR, RNOR, or Non-Resident.", LinkNode],
  ["7", "Income Deemed Received", "Specifies types of income legally treated as received in India regardless of physical payouts.", LinkNode],
  ["9", "Income Accruing in India", "Directs the taxability of income originating from Indian assets, business connections, or sources.", LinkNode],
  ["10", "Exempt Incomes", "Comprehensive index of incomes entirely excluded from the computation of gross total income.", LinkNode],
  ["10AA", "SEZ Tax Holiday", "Special tax incentives and deductions for units operating within Special Economic Zones.", LinkNode],
  ["11", "Charitable Trusts Income", "Conditions for tax exemptions on income derived from property held under public religious or charitable trusts.", LinkNode],
  ["12", "Voluntary Contributions", "Governs the taxability of voluntary donations received by registered charitable trusts.", LinkNode],
  ["13", "Forfeiture of Trust Exemption", "Specific statutory conditions under which charitable trusts forfeit their tax-exempt status.", LinkNode],
  ["14A", "Disallowance of Exempt Income Expense", "Restricts deductions for expenditures incurred directly or indirectly to earn tax-free income.", LinkNode],
  ["15", "Chargeability of Salary", "Establishes the basis of charging salary income on a due or receipt basis, whichever is earlier.", LinkNode],
  ["16", "Salary Deductions", "Statutory deductions allowed against salary income, including standard deduction and professional tax.", LinkNode],
  ["17", "Salary Definitions", "Comprehensive definitions of what constitutes standard salary, perquisites, and profits in lieu of salary.", LinkNode],
  ["22", "Chargeability of House Property", "Establishes tax chargeability on the annual value of lands or buildings owned by the assessee.", LinkNode],
  ["23", "Annual Value Determination", "Specifies the rules for calculating the net annual value of self-occupied, let-out, or deemed let-out properties.", LinkNode],
  ["24", "House Property Deductions", "Allowable deductions from annual house property value, covering standard repairs and home loan interest.", LinkNode],
  ["28", "Chargeability of PGBP", "The primary charging section for profits and gains derived from business or professional operations.", LinkNode],
  ["32", "Depreciation Allowance", "Statutory rules for claiming depreciation on blocks of tangible and intangible business assets.", LinkNode],
  ["35", "Scientific Research", "Deductions allowed for capital and revenue expenditures incurred on internal or sponsored scientific research.", LinkNode],
  ["36", "Specific Business Deductions", "A dedicated list of miscellaneous business expenditures allowed under strict operational conditions.", LinkNode],
  ["37", "General Business Deduction", "Residual clause allowing deductions for bona fide business expenditures not covered by other specific sections.", LinkNode],
  ["40", "Statutory Disallowances", "Restricts deductions for certain payments if tax is not deducted at source (TDS defaults) or paid properly.", LinkNode],
  ["40A", "Cash Payment & Excessive Expense Disallowance", "Provisions disallowing excessive payments to relatives and cash business expenditures crossing prescribed thresholds.", LinkNode],
  ["43B", "Actual Payment Deductions", "Mandates that specific liabilities (like statutory taxes or employee dues) are deductible only upon actual payment.", LinkNode],
  ["44AB", "Mandatory Tax Audit", "Prescribes compliance thresholds above which businesses and professionals must get accounts audited by a CA.", LinkNode],
  ["44AD", "Presumptive Business Income", "Concessional framework allowing small businesses to declare profits on a flat percentage of gross turnover.", LinkNode],
  ["44ADA", "Presumptive Professional Income", "Concessional tax framework for specified professionals to declare profits on a percentage of gross receipts.", LinkNode],
  ["44AE", "Presumptive Transport Income", "Simplified profit computation scheme for taxpayers engaged in the business of plying, hiring, or leasing goods carriages.", LinkNode],
  ["45", "Chargeability of Capital Gains", "Fundamental charging section for profits arising from the transfer of capital assets in the previous year.", LinkNode],
  ["47", "Transactions Not Regarded as Transfer", "Comprehensive list of asset transfers (e.g., gifts, wills, corporate restructuring) exempt from capital gains.", LinkNode],
  ["48", "Capital Gains Computation Mode", "Prescribes the core formula for computing capital gains by deducting acquisition, improvement, and selling costs.", LinkNode],
  ["49", "Cost Reference to Previous Owner", "Dictates how the cost of acquisition is computed when an asset is acquired via gift, inheritance, or trust.", LinkNode],
  ["50", "Depreciable Assets Capital Gains", "Special provisions for calculating capital gains on the transfer of business assets within a depreciable block.", LinkNode],
  ["50C", "Real Estate Stamp Value Full Value", "Substitutes the official stamp duty valuation as the full value of consideration if the declared sale price is lower.", LinkNode],
  ["50CA", "Unlisted Shares Full Value", "Deems the Fair Market Value (FMV) as the sale consideration for transfers of unlisted equity shares.", LinkNode],
  ["54", "Residential Property Reinvestment Exemption", "Exemption on long-term capital gains from a residential house when reinvested into another residential house.", LinkNode],
  ["54B", "Agricultural Land Reinvestment Exemption", "Capital gains relief granted when urban agricultural land is sold and reinvested into new agricultural land.", LinkNode],
  ["54D", "Compulsory Acquisition Exemption", "Relieves capital gains tax when industrial land or buildings are compulsorily acquired and replaced.", LinkNode],
  ["54EC", "Specified Bonds Reinvestment Exemption", "Capital gains tax exemption obtained by investing long-term real estate gains into specified infrastructure bonds.", LinkNode],
  ["54F", "Non-Residential Asset Reinvestment Exemption", "Long-term capital gains relief on selling any asset (other than a house) if net proceeds buy a residential home.", LinkNode],
  ["54GB", "Residential Company Equity Investment Exemption", "Relief on capital gains from residential property when invested in the equity of an eligible startup company.", LinkNode],
  ["56", "Income from Other Sources", "The residual head charging all taxable income types that do not legally fit into the other four heads (e.g., dividends, interest, specified gifts).", LinkNode],
  ["57", "Deductions from Other Sources", "Specifies the allowable deductions for expenses incurred directly to earn income chargeable under the residual head.", LinkNode],
  ["58", "Amounts Not Deductible", "Lists specific expenses and personal expenditures that cannot be claimed as deductions against income from other sources.", LinkNode],
  ["60", "Transfer of Income", "Mandates that if income is transferred to another person without transferring the underlying asset, the income is taxed in the hands of the transferor.", LinkNode],
  ["64", "Clubbing of Income", "Provisions where the income of specified persons (like a spouse, minor child, or daughter-in-law) is clubbed and taxed in the assessee's hands.", LinkNode],
  ["68", "Unexplained Cash Credits", "Taxes any sum credited in the taxpayer's books for which they can offer no satisfactory explanation regarding the source or nature.", LinkNode],
  ["69", "Unexplained Investments", "Provisions for taxing the value of investments made by the assessee that are not recorded in their books and lack a satisfactory explanation.", LinkNode],
  ["70", "Intra-head Set-Off", "Rules permitting the set-off of a loss from one source against income from another source within the same head of income.", LinkNode],
  ["71", "Inter-head Set-Off", "Governs the set-off of losses sustained under one head of income against income earned under a different head in the same assessment year.", LinkNode],
  ["71B", "Carry Forward: House Property", "Specifies the conditions and time limits for carrying forward unabsorbed losses from house property to future assessment years.", LinkNode],
  ["72", "Carry Forward: Business Losses", "Dictates the rules and time limits for carrying forward unabsorbed regular business losses to be set off against future business income.", LinkNode],
  ["73", "Speculation Business Losses", "Restricts the set-off and carry forward of losses from speculative businesses exclusively against profits from other speculative businesses.", LinkNode],
  ["74", "Carry Forward: Capital Losses", "Outlines the mechanism for carrying forward short-term and long-term capital losses, restricting their set-off only against future capital gains.", LinkNode],
  ["79", "Carry Forward: Closely Held Companies", "Restricts the carry forward of losses in certain closely held companies if there is a substantial change in their shareholding/voting power.", LinkNode],
  ["80C", "Investment Deductions", "Allows deductions from gross total income for specified tax-saving investments (e.g., PPF, EPF, LIC) and specified payments (e.g., tuition fees).", LinkNode],
  ["80CCC", "Pension Fund Contributions", "Provides a deduction for amounts paid towards specified annuity and pension plans offered by insurance companies.", LinkNode],
  ["80CCD", "National Pension System (NPS)", "Deductions for contributions made by an individual or their employer to the National Pension System (NPS) or Atal Pension Yojana.", LinkNode],
  ["80D", "Health Insurance Premium", "Deduction for medical insurance premiums paid for self, spouse, dependent children, and parents, as well as preventive health check-ups.", LinkNode],
  ["80DD", "Disabled Dependent Maintenance", "Deduction for expenses incurred on the medical treatment, training, and rehabilitation of a dependent person with a disability.", LinkNode],
  ["80DDB", "Specified Disease Treatment", "Allows a deduction for medical expenditures incurred on the treatment of specified severe ailments or diseases for self or dependents.", LinkNode],
  ["80E", "Education Loan Interest", "Provides a deduction for the interest paid on an education loan taken for the higher education of self, spouse, or children.", LinkNode],
  ["80EEA", "Affordable Housing Loan Interest", "Additional deduction for interest paid on housing loans sanctioned during a specified period for purchasing affordable residential house property.", LinkNode],
  ["80EEB", "Electric Vehicle Loan Interest", "Deduction available for interest paid on loans taken specifically for the purchase of an electric vehicle.", LinkNode],
  ["80G", "Charitable Donations", "Deductions allowed for monetary donations made to prescribed charitable institutions, trusts, and government relief funds.", LinkNode],
  ["80GG", "House Rent Paid", "Relief for taxpayers who pay house rent but do not receive a House Rent Allowance (HRA) as part of their salary structure.", LinkNode],
  ["80GGA", "Donations for Scientific Research", "Deduction for donations made to eligible institutions for scientific research or rural development programs.", LinkNode],
  ["80GGB/C", "Political Contributions", "Allows companies (80GGB) and other persons (80GGC) to claim deductions for contributions made to registered political parties or electoral trusts.", LinkNode],
  ["80JJAA", "Employment of New Employees", "Incentive deduction based on additional employee cost incurred by businesses that generate new formal employment.", LinkNode],
  ["80TTA", "Savings Account Interest", "Provides a standard deduction on interest earned from savings bank accounts for individuals and HUFs (excluding senior citizens).", LinkNode],
  ["80TTB", "Senior Citizen Deposit Interest", "Provides a higher deduction threshold for senior citizens on interest income earned from savings accounts and fixed deposits.", LinkNode],
  ["80U", "Disabled Individual Deduction", "A flat deduction available directly to a resident individual who is certified by a medical authority to be suffering from a disability.", LinkNode],
  ["87A", "Tax Rebate", "Provides a tax rebate for resident individuals whose total taxable income falls below a specified threshold, effectively reducing their tax liability to nil.", LinkNode],
  ["89", "Relief for Salary Arrears", "Grants tax relief when a taxpayer receives salary in arrears or in advance, preventing them from being taxed at a higher slab rate due to a lump-sum payout.", LinkNode],
  ["90", "Double Taxation Relief (DTAA)", "Provisions enabling the Central Government to enter into agreements with foreign countries to prevent double taxation of the same income.", LinkNode],
  ["92", "Transfer Pricing", "Mandates that any income arising from an international transaction (or specified domestic transaction) between associated enterprises shall be computed at an arm's length price.", LinkNode],
  ["111A", "Special Rate: Short-Term Capital Gains", "Prescribes a special, concessional tax rate for short-term capital gains arising from the transfer of specified listed equity shares and equity-oriented funds.", LinkNode],
  ["112", "Special Rate: Long-Term Capital Gains", "General provision dictating the special tax rate for long-term capital gains on assets not covered under Section 112A.", LinkNode],
  ["112A", "Special Rate: LTCG on Equities", "Prescribes the tax framework and special rate for long-term capital gains exceeding a specified threshold on listed equity shares and equity-oriented funds.", LinkNode],
  ["115BAC", "New/Concessional Tax Regime", "Outlines the alternative tax regime offering concessional slab rates for individuals, HUFs, and AOPs, conditional upon foregoing certain exemptions and deductions.", LinkNode],
  ["115BB", "Winnings from Lotteries & Games", "Prescribes a flat, elevated tax rate on income derived from lotteries, crossword puzzles, races, card games, and other games of any sort.", LinkNode],
  ["115BBE", "Tax on Unexplained Income", "Applies a high, punitive tax rate (plus surcharge) to income assessed as unexplained cash credits, investments, or expenditures under sections 68 to 69D.", LinkNode],
  ["115JB", "Minimum Alternate Tax (MAT)", "Mandates that if a company's normal tax liability is lower than a specified percentage of its \"book profit,\" the book profit is deemed to be total income and taxed accordingly.", LinkNode],
  ["139", "Return of Income", "The foundational section mandating the filing of an Income Tax Return (ITR), specifying due dates for different categories of taxpayers, and rules for belated or revised returns.", LinkNode],
  ["139AA", "Quoting of Aadhaar Number", "Mandates the quoting of an Aadhaar number in the ITR and PAN application, and requires the linking of PAN with Aadhaar.", LinkNode],
  ["140A", "Self-Assessment Tax", "Requires a taxpayer to calculate and pay any outstanding tax and interest before filing their return of income.", LinkNode],
  ["142", "Inquiry Before Assessment", "Empowers tax authorities to issue notices requiring taxpayers to produce accounts, documents, or information before an assessment is finalized.", LinkNode],
  ["143", "Assessment Procedures", "Covers the automated processing of returns (intimations), the issuance of scrutiny notices, and the procedures for regular scrutiny assessments.", LinkNode],
  ["144", "Best Judgment Assessment", "Empowers the Assessing Officer to estimate income and assess tax to the best of their judgment if the taxpayer fails to file a return or comply with notices.", LinkNode],
  ["147", "Income Escaping Assessment", "Grants the department the power to reopen past assessments or assess income if they have reason to believe income chargeable to tax has escaped assessment.", LinkNode],
  ["148", "Notice for Reassessment", "Mandates the issuance of a formal notice to the taxpayer before initiating any proceedings to assess or reassess escaped income under Section 147.", LinkNode],
  ["154", "Rectification of Mistakes", "Allows the tax authorities or the taxpayer to rectify any mistake apparent from the record in any order, intimation, or assessment passed.", LinkNode],
  ["156", "Notice of Demand", "The statutory notice issued by the tax department demanding payment of any tax, interest, penalty, or fine determined to be payable by the assessee.", LinkNode],
  ["192", "TDS on Salary", "Obligates employers to accurately estimate an employee's annual income and deduct tax at source at the average rate applicable.", LinkNode],
  ["194A", "TDS on Interest", "Requires the deduction of tax at source on interest income (other than interest on securities), typically applied by banks on fixed deposits.", LinkNode],
  ["194BA", "TDS on Online Games", "Specific provision for deducting tax at source on net winnings from online games at the end of the financial year or upon withdrawal.", LinkNode],
  ["194C", "TDS on Contractors", "Mandates tax deduction at source on payments made to resident contractors and sub-contractors for carrying out any physical or ad-agency work.", LinkNode],
  ["194H", "TDS on Commission", "Requires the deduction of tax at source on payments made by way of commission or brokerage (excluding insurance commission).", LinkNode],
  ["194I", "TDS on Rent", "Obligates specified persons paying rent for land, building, machinery, or equipment to deduct tax at source once it crosses a monetary threshold.", LinkNode],
  ["194J", "TDS on Professional/Technical Fees", "Mandates TDS on payments made for professional services, technical services, royalties, or directors' remuneration.", LinkNode],
  ["194Q", "TDS on Purchase of Goods", "Requires large buyers (based on turnover) to deduct tax at source when purchasing goods from a resident seller exceeding a specified aggregate value.", LinkNode],
  ["194S", "TDS on Virtual Digital Assets (Crypto)", "Obligates the deduction of tax at source on payments made for the transfer of a virtual digital asset (VDA/cryptocurrency).", LinkNode],
  ["195", "TDS on Non-Resident Payments", "A broad provision requiring anyone making a payment (chargeable to tax in India) to a non-resident or foreign company to deduct tax at source.", LinkNode],
  ["206AA", "Higher TDS for Non-furnishing of PAN", "Mandates that if a payee fails to furnish their PAN, the tax shall be deducted at the higher of the prescribed rate or a statutory penal rate.", LinkNode],
  ["206AB", "Higher TDS for Non-Filers", "Imposes higher rates of TDS on specified payments made to \"specified persons\" who have not filed their income tax returns for previous years.", LinkNode],
  ["206C", "Tax Collection at Source (TCS)", "Requires sellers of specified goods (e.g., scrap, timber, motor vehicles over a certain value) and authorized dealers handling overseas remittances to collect tax from the buyer.", LinkNode],
  ["208", "Advance Tax Liability", "Establishes the threshold condition: advance tax must be paid if the estimated tax liability for the year exceeds a specified monetary limit.", LinkNode],
  ["211", "Advance Tax Installments", "Prescribes the quarterly due dates and the cumulative percentage of the total advance tax liability that must be paid by each date.", LinkNode],
  ["234A", "Interest for Late Filing", "Levies penal interest for the delay or default in furnishing the return of income beyond the statutory due date.", LinkNode],
  ["234B", "Interest for Default in Advance Tax", "Levies interest if a taxpayer fails to pay advance tax or if the advance tax paid is less than 90% of the assessed tax.", LinkNode],
  ["234C", "Interest for Deferment of Advance Tax", "Levies interest for shortfalls in the payment of individual quarterly advance tax installments.", LinkNode],
  ["234F", "Late Filing Fee", "Prescribes a mandatory late fee for filing the income tax return after the prescribed due date.", LinkNode],
  ["246A", "Appeal to CIT(A)", "Outlines the rights and procedures for a taxpayer to file the first stage of appeal before the Commissioner of Income Tax (Appeals) against an assessing officer's order.", LinkNode],
  ["253", "Appeal to ITAT", "Outlines the rights to file a second appeal before the Income Tax Appellate Tribunal (ITAT) against the orders passed by the CIT(A).", LinkNode],
  ["270A", "Penalty for Under-reporting", "Imposes strict, graded penalty mechanisms for the under-reporting and misreporting of income detected during assessment.", LinkNode],
  ["276C", "Prosecution for Tax Evasion", "Details the legal consequences, including rigorous imprisonment and fines, for willful attempts to evade any tax, penalty, or interest chargeable under the Act.", LinkNode],
  ["72A", "Business Restructuring Losses", "Provisions governing the carry forward and set-off of accumulated losses and unabsorbed depreciation in cases of amalgamation, demerger, or reorganization.", LinkNode],
  ["90A", "Tax Relief via Specified Associations", "Enables tax relief and double taxation avoidance agreements matching arrangements made with specified associations in a reciprocal country outside India.", LinkNode],
  ["94", "Avoidance of Tax via Securities", "Anti-avoidance provisions targeting bond-washing transactions and dividend stripping practices to prevent artificial tax losses.", LinkNode],
  ["96", "General Anti-Avoidance Rule (GAAR)", "Defines an \"impermissible avoidance arrangement\" and empowers tax authorities to restructure transactions entered into primarily to obtain a tax benefit.", LinkNode],
  ["115JC", "Alternate Minimum Tax (AMT)", "Compulsory tax framework requiring non-corporate taxpayers claiming specified deductions to pay an alternate minimum tax based on adjusted total income.", LinkNode],
  ["115O / 115R", "Distribution Taxes", "Provisions governing the levy, chargeability, and remittance obligations concerning domestic corporate profit and mutual fund income distributions.", LinkNode],
  ["115UA", "Business Trusts (REITs/InvITs)", "Special pass-through tax regime governing the characterization and taxability of income distributed by Real Estate Investment Trusts and Infrastructure Investment Trusts.", LinkNode],
  ["132", "Search and Seizure", "Statutory powers granted to tax authorities to enter, search premises, and seize unaccounted books, documents, cash, or assets where tax evasion is suspected.", LinkNode],
  ["160", "Representative Assessee", "Defines status and liabilities where a person is legally taxed as an agent or representative on behalf of minors, lunatics, non-residents, or trusts.", LinkNode],
  ["184", "Assessment of Partnership Firms", "Prescribes the compliance conditions a partnership firm must fulfill to be assessed as a firm rather than an association of persons.", LinkNode],
  ["263", "Revision by Commissioner", "Empowers the Principal Commissioner or Commissioner to revise any order passed by an Assessing Officer if it is deemed erroneous and prejudicial to the interests of revenue.", LinkNode],
  ["264", "Revision in Favor of Assessee", "Empowers the Commissioner to revise orders either on their own motion or on an application by the taxpayer to grant administrative relief.", LinkNode],
  ["269SS", "Restriction on Accepting Cash Loans", "Prohibits taxpayers from accepting loans, deposits, or specified sums in cash above a prescribed statutory threshold from any other person.", LinkNode],
  ["269T", "Restriction on Repaying Cash Loans", "Prohibits the repayment of loans, deposits, or specified advances in cash above a statutory threshold, making electronic clearance mandatory.", LinkNode],
  ["269ST", "General Cash Receipt Restraints", "Restricts any person from receiving an aggregate cash sum crossing prescribed limits in a single day, from a single transaction, or in respect of distinct events.", LinkNode]
];

export const IncomeTaxAct: React.FC = () => {
  return (
    <ResourceLayout
      title="Income Tax Act"
      description="Important and frequently used sections of the Income-tax Act."
      data={pageData}
      type="table"
      headers={["Section", "Topic", "Description", "Link"]}
    />
  );
};
